### PR TITLE
Fix #92, Use size_t for 'size' variables

### LINKED ISSUE #92: Use size_t for 'size' variables
**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [x] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the bug**
Most variables representing sizes in FM use size_t.
There are a few that do not follow this custom and could be transitioned over.

**Code snips**
https://github.com/nasa/FM/blob/2be3511211e756058236b30abe40b0de372bd2f1/fsw/src/fm_child.c#L1396
https://github.com/nasa/FM/blob/2be3511211e756058236b30abe40b0de372bd2f1/fsw/src/fm_cmd_utils.c#L161

**Expected behavior**
All size variables that can use size_t should do so - size_t is more expressive and more consistent with the relevant coding guidelines.

**Reporter Info**
Avi Weiss @thnkslprpt

### PR DESCRIPTION
**Pull request by thnkslprpt**
**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/osal/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
Fixes #92 
Easy-to-find size variables converted to `size_t` type.

All except the local variables in `FM_ChildDirListPktCmd()` and `FM_ChildDirListFileLoop()` were already of type `uint32`, so no real risk of signedness issues popping up.

Note: I did not scrub the entire app - if someone can suggest some additional variables to convert over to `size_t` I can add them to this PR.

A few typos and spacing issues cleared up in the same files.

**Testing performed**
GitHub CI actions (incl. Build + Run, Unit Tests etc.) all passing successfully.

**Expected behavior changes**
Variables representing size should use `size_t` where possible - more expressive and more compliant with the various (relevant) coding guidelines.

**Contributor Info**
Avi Weiss @thnkslprpt

### CODE REVIEW

File: fsw/src/fm_cmd_utils.h [hunk 1]
```diff
@@ -346,7 +346,7 @@ bool FM_VerifyChildTask(uint32 EventID, const char *CmdText);
  *       available entry in the child task queue with the arguments for
  *       the current command.  The function updates the queue access
  *       index and then verifies that the Child Task is operational.
- *       If the Child Task is operational then it is signaled via
+ *       If the Child Task is operational then it is signalled via
```
Comment (dzbaker) [inline fsw/src/fm_cmd_utils.h]: Signaled is actually the correct spelling (in American English; British English uses 2 'l's)

**Review by dzbaker — CHANGES_REQUESTED** [review]

File: fsw/src/fm_cmd_utils.h (hunk 1 above)
Comment (thnkslprpt) [reply fsw/src/fm_cmd_utils.h]: Woops - don't know how that snuck in there.
My family is a hybrid of both sides of the Atlantic...
Changed back now :-)

**Review by dzbaker — APPROVED** [review]

**Comment by dzbaker** [comment]
@thnkslprpt CCB 30 March 2023: Approved pending conflict resolution.

**Comment by thnkslprpt** [comment]
> @thnkslprpt CCB 30 March 2023: Approved pending conflict resolution.

All done @dzbaker.
Cheers
